// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Agents.AI.Workflows;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Microsoft.Shared.DiagnosticIds;

namespace Microsoft.Agents.AI.Foundry.Hosting;

/// <summary>
/// Readiness health check that, on a resilient host, reports unhealthy when a workflow hosted as an
/// agent has one or more steps whose agent has an auto-generated id.
/// </summary>
/// <remarks>
/// <para>
/// Crash-recovery resume matches the saved checkpoint to the rebuilt workflow by executor id (see
/// <c>WorkflowInfo.IsMatch</c>). An agent-backed executor derives its id from the agent's
/// <see cref="AIAgent.Id"/>, which, when the caller supplies no explicit id, defaults to a fresh
/// random value per process. A workflow built from such agents produces different ids on every
/// start, so after a container restart the resumed run fails deep in the engine with "the specified
/// checkpoint is not compatible with the workflow".
/// </para>
/// <para>
/// This check turns that late, cryptic failure into an early, actionable not-ready signal: while
/// <see cref="Azure.AI.AgentServer.Responses.ResponsesServerOptions.ResilientBackground"/> is on, it
/// inspects every registered workflow-host agent (via <c>agent.GetService&lt;Workflow&gt;()</c>) and
/// fails readiness if any agent-backed step has an auto-generated id
/// (<see cref="AIAgent.HasAutoGeneratedId"/>). This is authoritative: a caller-supplied id that
/// happens to be a GUID is correctly treated as stable. On a non-resilient host it is a no-op
/// (always healthy), because unstable ids are harmless when there is no recovery. It has no side
/// effects: it reads already-constructed agent instances and never creates a session.
/// </para>
/// </remarks>
[Experimental(DiagnosticIds.Experiments.AgentsAIExperiments)]
internal sealed class ResilientWorkflowExecutorIdHealthCheck : IHealthCheck
{
    private readonly Func<bool> _isResilient;
    private readonly Func<IEnumerable<AIAgent>> _agents;

    public ResilientWorkflowExecutorIdHealthCheck(Func<bool> isResilient, Func<IEnumerable<AIAgent>> agents)
    {
        ArgumentNullException.ThrowIfNull(isResilient);
        ArgumentNullException.ThrowIfNull(agents);
        this._isResilient = isResilient;
        this._agents = agents;
    }

    public Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default)
    {
        // Unstable executor ids only matter when the host can recover a run after a restart.
        if (!this._isResilient())
        {
            return Task.FromResult(HealthCheckResult.Healthy(
                description: "Resilient workflow ids: not applicable (ResilientBackground is off)."));
        }

        List<string>? offenders = null;
        foreach (var agent in this._agents())
        {
            if (agent.GetService<Workflow>() is not { } workflow)
            {
                // Not a workflow-host agent; single agents have no internal executor ids to match.
                continue;
            }

            foreach (var (executorId, binding) in workflow.ReflectExecutors())
            {
                // An agent-backed executor exposes its agent as the binding's raw value. Only those
                // derive an id from an AIAgent, so only those can carry an auto-generated id.
                if (binding.RawValue is AIAgent stepAgent && stepAgent.HasAutoGeneratedId)
                {
                    (offenders ??= []).Add($"agent '{agent.Name ?? agent.Id}' step '{executorId}'");
                }
            }
        }

        if (offenders is null)
        {
            return Task.FromResult(HealthCheckResult.Healthy(
                description: "Resilient workflow ids: all hosted workflow steps have stable ids."));
        }

        return Task.FromResult(new HealthCheckResult(
            status: context.Registration.FailureStatus,
            description:
                $"Resilient workflow ids: one or more hosted workflow steps use an agent with an auto-generated id, which breaks crash-recovery resume (the checkpoint is matched to the rebuilt workflow by executor id, and an auto-generated id changes on every restart). Assign a stable Id to each agent in the workflow, for example chatClient.AsAIAgent(options: new() {{ Id = \"translator\", Name = \"translator\" }}). Offending steps: {string.Join("; ", offenders)}."));
    }
}
