// Copyright (c) Microsoft. All rights reserved.

using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Agents.Workflows;
using Microsoft.Agents.Workflows.Reflection;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.AI.Agents;
using Microsoft.Shared.Samples;

namespace Workflow;

/// <summary>
/// This sample introduces conditional routing using edge conditions to create decision-based workflows.
///
/// This workflow creates an automated email response system that routes emails down different paths based
/// on spam detection results:
///
/// 1. Spam Detection Agent analyzes incoming emails and classifies them as spam or legitimate
/// 2. Based on the classification:
///    - Legitimate emails → Email Assistant Agent → Send Email Executor
///    - Spam emails → Handle Spam Executor (marks as spam)
///
/// Edge conditions enable workflows to make intelligent routing decisions, allowing you to
/// build sophisticated automation that responds differently based on the data being processed.
/// </summary>
/// <remarks>
/// Pre-requisites:
/// - Foundational samples must be completed first.
/// - Shared state is used in this sample to persist email data between executors.
/// - An Azure OpenAI chat completion deployment that supports structured outputs must be configured.
/// </remarks>
public class EdgeCondition(ITestOutputHelper output) : WorkflowSample(output)
{
    private const string EmailStateScope = "EmailState";

    [Fact]
    public async Task RunAsync()
    {
        // Create agents
        AIAgent spamDetectionAgent = GetSpamDetectionAgent();
        AIAgent emailAssistantAgent = GetEmailAssistantAgent();

        // Create executors
        var spamDetectionExecutor = new SpamDetectionExecutor(spamDetectionAgent);
        var emailAssistantExecutor = new EmailAssistantExecutor(emailAssistantAgent);
        var sendEmailExecutor = new SendEmailExecutor();
        var handleSpamExecutor = new HandleSpamExecutor();

        // Build the workflow
        WorkflowBuilder builder = new(spamDetectionExecutor);
        builder.AddEdge(spamDetectionExecutor, emailAssistantExecutor, condition: GetCondition(expectedResult: false));
        builder.AddEdge(emailAssistantExecutor, sendEmailExecutor);
        builder.AddEdge(spamDetectionExecutor, handleSpamExecutor, condition: GetCondition(expectedResult: true));
        var workflow = builder.Build<ChatMessage>();

        // Read a email from a text file
        string email = Resources.Read("spam.txt");

        // Execute the workflow
        StreamingRun run = await InProcessExecution.StreamAsync(workflow, new ChatMessage(ChatRole.User, email));
        await run.TrySendMessageAsync(new TurnToken(emitEvents: true));
        await foreach (WorkflowEvent evt in run.WatchStreamAsync().ConfigureAwait(false))
        {
            if (evt is WorkflowCompletedEvent completedEvent)
            {
                Console.WriteLine($"{completedEvent}");
            }
        }
    }

    /// <summary>
    /// Represents the result of spam detection.
    /// </summary>
    public sealed class DetectionResult
    {
        [JsonPropertyName("is_spam")]
        public bool IsSpam { get; set; }

        [JsonPropertyName("reason")]
        public string Reason { get; set; } = string.Empty;

        // Email ID is generated by the executor not the agent
        [JsonIgnore]
        public string EmailId { get; set; } = string.Empty;
    }

    /// <summary>
    /// Represents an email.
    /// </summary>
    private sealed class Email
    {
        [JsonPropertyName("email_id")]
        public string EmailId { get; set; } = string.Empty;

        [JsonPropertyName("email_content")]
        public string EmailContent { get; set; } = string.Empty;
    }

    /// <summary>
    /// Creates a condition for routing messages based on the expected spam detection result.
    /// </summary>
    /// <param name="expectedResult">The expected spam detection result</param>
    /// <returns>A function that evaluates whether a message meets the expected result</returns>
    private Func<object?, bool> GetCondition(bool expectedResult)
    {
        return detectionResult =>
        {
            return detectionResult is DetectionResult result && result.IsSpam == expectedResult;
        };
    }

    /// <summary>
    /// Creates a spam detection agent.
    /// </summary>
    /// <returns>A ChatClientAgent configured for spam detection</returns>
    private ChatClientAgent GetSpamDetectionAgent()
    {
        string instructions = "You are a spam detection assistant that identifies spam emails.";
        var agentOptions = new ChatClientAgentOptions(instructions: instructions)
        {
            ChatOptions = new()
            {
                ResponseFormat = ChatResponseFormatJson.ForJsonSchema(
                    schema: AIJsonUtilities.CreateJsonSchema(typeof(DetectionResult))
                )
            }
        };

        return new ChatClientAgent(GetAzureOpenAIChatClient(), agentOptions);
    }

    /// <summary>
    /// Executor that detects spam using an AI agent.
    /// </summary>
    private sealed class SpamDetectionExecutor : ReflectingExecutor<SpamDetectionExecutor>, IMessageHandler<ChatMessage, DetectionResult>
    {
        private readonly AIAgent _spamDetectionAgent;

        /// <summary>
        /// Creates a new instance of the <see cref="SpamDetectionExecutor"/> class.
        /// </summary>
        /// <param name="spamDetectionAgent">The AI agent used for spam detection</param>
        public SpamDetectionExecutor(AIAgent spamDetectionAgent) : base("SpamDetectionExecutor")
        {
            _spamDetectionAgent = spamDetectionAgent;
        }

        public async ValueTask<DetectionResult> HandleAsync(ChatMessage message, IWorkflowContext context)
        {
            // Generate a random email ID and store the email content to the shared state
            var newEmail = new Email
            {
                EmailId = Guid.NewGuid().ToString(),
                EmailContent = message.Text
            };
            await context.QueueStateUpdateAsync<Email>(newEmail.EmailId, newEmail, scopeName: EmailStateScope);

            // Invoke the agent
            var response = await _spamDetectionAgent.RunAsync(message);
            var detectionResult = JsonSerializer.Deserialize<DetectionResult>(response.Text);

            detectionResult!.EmailId = newEmail.EmailId;

            return detectionResult;
        }
    }

    /// <summary>
    /// Represents the response from the email assistant.
    /// </summary>
    public sealed class EmailResponse
    {
        [JsonPropertyName("response")]
        public string Response { get; set; } = string.Empty;
    }

    /// <summary>
    /// Creates an email assistant agent.
    /// </summary>
    /// <returns>A ChatClientAgent configured for email assistance</returns>
    private ChatClientAgent GetEmailAssistantAgent()
    {
        string instructions = "You are an email assistant that helps users draft responses to emails with professionalism.";
        var agentOptions = new ChatClientAgentOptions(instructions: instructions)
        {
            ChatOptions = new()
            {
                ResponseFormat = ChatResponseFormatJson.ForJsonSchema(
                    schema: AIJsonUtilities.CreateJsonSchema(typeof(EmailResponse))
                )
            }
        };

        return new ChatClientAgent(GetAzureOpenAIChatClient(), agentOptions);
    }

    /// <summary>
    /// Executor that assists with email responses using an AI agent.
    /// </summary>
    private sealed class EmailAssistantExecutor : ReflectingExecutor<EmailAssistantExecutor>, IMessageHandler<DetectionResult, EmailResponse>
    {
        private readonly AIAgent _emailAssistantAgent;

        /// <summary>
        /// Creates a new instance of the <see cref="EmailAssistantExecutor"/> class.
        /// </summary>
        /// <param name="emailAssistantAgent">The AI agent used for email assistance</param>
        public EmailAssistantExecutor(AIAgent emailAssistantAgent) : base("EmailAssistantExecutor")
        {
            _emailAssistantAgent = emailAssistantAgent;
        }

        public async ValueTask<EmailResponse> HandleAsync(DetectionResult message, IWorkflowContext context)
        {
            if (message.IsSpam)
            {
                throw new InvalidOperationException("This executor should only handle non-spam messages.");
            }

            // Retrieve the email content from the shared state
            var email = await context.ReadStateAsync<Email>(message.EmailId, scopeName: EmailStateScope)
                ?? throw new InvalidOperationException("Email not found.");

            // Invoke the agent
            var response = await _emailAssistantAgent.RunAsync(email.EmailContent);
            var emailResponse = JsonSerializer.Deserialize<EmailResponse>(response.Text);

            return emailResponse!;
        }
    }

    /// <summary>
    /// Executor that sends emails.
    /// </summary>
    private sealed class SendEmailExecutor() : ReflectingExecutor<SendEmailExecutor>("SendEmailExecutor"), IMessageHandler<EmailResponse>
    {
        /// <summary>
        /// Simulate the sending of an email.
        /// </summary>
        public async ValueTask HandleAsync(EmailResponse message, IWorkflowContext context)
        {
            await context.AddEventAsync(new WorkflowCompletedEvent($"Email sent: {message.Response}"));
        }
    }

    /// <summary>
    /// Executor that handles spam messages.
    /// </summary>
    private sealed class HandleSpamExecutor() : ReflectingExecutor<HandleSpamExecutor>("HandleSpamExecutor"), IMessageHandler<DetectionResult>
    {
        /// <summary>
        /// Simulate the handling of a spam message.
        /// </summary>
        public async ValueTask HandleAsync(DetectionResult message, IWorkflowContext context)
        {
            if (message.IsSpam)
            {
                await context.AddEventAsync(new WorkflowCompletedEvent($"Email marked as spam: {message.Reason}"));
            }
            else
            {
                throw new InvalidOperationException("This executor should only handle spam messages.");
            }
        }
    }
}
