// Copyright (c) Microsoft. All rights reserved.

// This sample shows how to use the Responses API Web Search Tool with AI Agents.

using Azure.AI.Projects.OpenAI;
using Azure.Identity;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using OpenAI.Responses;

string endpoint = Environment.GetEnvironmentVariable("AZURE_AI_PROJECT_ENDPOINT") ?? throw new InvalidOperationException("AZURE_AI_PROJECT_ENDPOINT is not set.");
string deploymentName = Environment.GetEnvironmentVariable("AZURE_AI_MODEL_DEPLOYMENT_NAME") ?? "gpt-4o-mini";

const string AgentInstructions = "You are a helpful assistant that can search the web to find current information and answer questions accurately.";

// Create a Foundry project Responses API client.
IChatClient chatClient = new ProjectResponsesClient(
    projectEndpoint: new Uri(endpoint),
    tokenProvider: new DefaultAzureCredential())
    .AsIChatClient();

// Option 1 - Using HostedWebSearchTool (MEAI + AgentFramework)
ChatClientAgent agent = new(chatClient, new ChatClientAgentOptions
{
    Name = "WebSearchAgent",
    ChatOptions = new()
    {
        ModelId = deploymentName,
        Instructions = AgentInstructions,
        Tools = [new HostedWebSearchTool()]
    },
});

// Option 2 - Using ResponseTool.CreateWebSearchTool converted via AsAITool (Native SDK type)
// ChatClientAgent agent = new(chatClient, new ChatClientAgentOptions
// {
//     Name = "WebSearchAgent",
//     ChatOptions = new()
//     {
//         ModelId = deploymentName,
//         Instructions = AgentInstructions,
//         Tools = [ResponseTool.CreateWebSearchTool().AsAITool()]
//     },
// });

AgentResponse response = await agent.RunAsync("What's the weather today in Seattle?");

// Get the text response
Console.WriteLine($"Response: {response.Text}");

// Getting any annotations/citations generated by the web search tool
foreach (AIAnnotation annotation in response.Messages.SelectMany(m => m.Contents).SelectMany(c => c.Annotations ?? []))
{
    Console.WriteLine($"Annotation: {annotation}");
    if (annotation.RawRepresentation is UriCitationMessageAnnotation urlCitation)
    {
        Console.WriteLine($$"""
            Title: {{urlCitation.Title}}
            URL: {{urlCitation.Uri}}
            """);
    }
}
