# Copyright (c) Microsoft. All rights reserved.

"""Durable naming helpers for hosting MAF Workflows.

A hosted workflow maps to durable primitives (an orchestration, plus an activity
or entity per executor) whose names must be **stable** across worker restarts:
durable replay only resumes an in-flight orchestration if the orchestration,
activity, and entity names still resolve to the same functions. This module
centralizes how those names are derived from a workflow name so every host (the
Azure Functions host and the standalone durabletask worker) and the client agree
on one scheme.

Naming scheme (the orchestration name is aligned byte-for-byte with .NET's
``WorkflowNamingHelper``)::

    orchestration:       dafx-{workflowName}
    non-agent activity:  dafx-{workflowName}-{executorId}   (wired up in Phase 1)
    agent entity:        dafx-{workflowName}-{executorId}   (wired up in Phase 1)

The orchestration name is the identifier the Durable Task tooling/UI surfaces, so
it matches .NET exactly. The inner activity/entity names are scoped by workflow in
Python (unlike .NET's bare ``dafx-{executorId}``) so two co-hosted workflows that
reuse an executor id cannot collide. See
``docs/design/durabletask-multiworkflow-and-subworkflows.md`` for the rationale.
"""

from __future__ import annotations

import re

__all__ = [
    "DURABLE_NAME_PREFIX",
    "is_auto_generated_workflow_name",
    "validate_workflow_name",
    "workflow_executor_activity_name",
    "workflow_name_from_orchestrator",
    "workflow_orchestrator_name",
    "workflow_scoped_executor_id",
]

# Shared prefix for every durable name this hosting layer registers. Matches
# .NET's ``WorkflowNamingHelper.OrchestrationFunctionPrefix`` and the existing
# ``AgentSessionId.ENTITY_NAME_PREFIX``.
DURABLE_NAME_PREFIX = "dafx-"

# A workflow name is interpolated into durable orchestration/activity/entity names
# *and* into HTTP route segments (``workflow/{workflowName}/run``), so it must be
# conservative enough to be safe in every position: ASCII letters, digits, '_' or
# '-', starting with a letter, at most 63 characters. The length cap leaves room
# for the ``dafx-`` prefix and an ``-{executorId}`` suffix within typical durable
# name limits.
_WORKFLOW_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,62}$")

# Names auto-generated by ``WorkflowBuilder`` when the caller does not pass one,
# e.g. ``"WorkflowBuilder-3f2b1c0a-1234-5678-9abc-def012345678"``. They embed a
# fresh ``uuid4`` per process build, so they are not stable identities and must be
# rejected for durable hosting (see :func:`validate_workflow_name`).
_AUTO_GENERATED_NAME_RE = re.compile(
    r"^WorkflowBuilder-[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
)


def workflow_orchestrator_name(workflow_name: str) -> str:
    """Return the durable orchestration name for a workflow.

    Args:
        workflow_name: The workflow's name. Must satisfy
            :func:`validate_workflow_name`.

    Returns:
        ``"dafx-{workflow_name}"``.

    Raises:
        ValueError: If ``workflow_name`` is not a valid, stable workflow name.
    """
    validate_workflow_name(workflow_name)
    return f"{DURABLE_NAME_PREFIX}{workflow_name}"


def workflow_name_from_orchestrator(orchestrator_name: str) -> str | None:
    """Recover the workflow name from a durable orchestration name.

    The inverse of :func:`workflow_orchestrator_name`. Intended to be applied to
    orchestration names (for example a durable instance's ``status.name``); it
    strips the shared :data:`DURABLE_NAME_PREFIX`.

    Args:
        orchestrator_name: A durable orchestration name.

    Returns:
        The workflow name, or ``None`` if ``orchestrator_name`` does not carry the
        expected prefix (so a caller can treat it as "not one of ours").
    """
    if not orchestrator_name.startswith(DURABLE_NAME_PREFIX):
        return None
    name = orchestrator_name[len(DURABLE_NAME_PREFIX) :]
    return name or None


def workflow_scoped_executor_id(workflow_name: str, executor_id: str) -> str:
    """Return the workflow-scoped identity for an executor.

    Inner executors (non-agent activities and agent entities) are scoped by
    workflow so two co-hosted workflows that reuse an ``executor_id`` register and
    dispatch to distinct durable primitives instead of colliding on one global
    name. This is the **unprefixed** identity (e.g. used as
    :class:`~agent_framework_durabletask.AgentSessionId` ``name``, which the entity
    layer then prefixes); see :func:`workflow_executor_activity_name` for the full
    activity function name.

    Args:
        workflow_name: The owning workflow's name.
        executor_id: The executor's id within that workflow.

    Returns:
        ``"{workflow_name}-{executor_id}"``.
    """
    return f"{workflow_name}-{executor_id}"


def workflow_executor_activity_name(workflow_name: str, executor_id: str) -> str:
    """Return the durable activity function name for a non-agent executor.

    Args:
        workflow_name: The owning workflow's name.
        executor_id: The executor's id within that workflow.

    Returns:
        ``"dafx-{workflow_name}-{executor_id}"``.
    """
    return f"{DURABLE_NAME_PREFIX}{workflow_scoped_executor_id(workflow_name, executor_id)}"


def validate_workflow_name(workflow_name: str) -> None:
    """Validate that a workflow name is usable as a stable durable identity.

    The name is **validated and rejected** rather than silently sanitized. A
    workflow name is an identity baked into durable orchestration/activity/entity
    names and HTTP routes, so transforming it could either (a) collapse two
    distinct names into one and reintroduce the cross-workflow collision this
    scheme exists to prevent, or (b) change the resolved name across versions and
    break resume of in-flight instances. A loud error is safer than a silent
    rename.

    Args:
        workflow_name: The candidate name.

    Raises:
        ValueError: If the name is empty, an auto-generated ``WorkflowBuilder``
            name, or contains characters outside
            ``[A-Za-z][A-Za-z0-9_-]{0,62}``.
    """
    if not workflow_name:
        raise ValueError("Workflow name must be a non-empty string.")
    if is_auto_generated_workflow_name(workflow_name):
        raise ValueError(
            f"Workflow name '{workflow_name}' is an auto-generated WorkflowBuilder name, which is "
            "not stable across restarts. Pass an explicit, stable name to WorkflowBuilder(name=...) "
            "before hosting the workflow durably."
        )
    if not _WORKFLOW_NAME_RE.match(workflow_name):
        raise ValueError(
            f"Workflow name '{workflow_name}' is invalid. Use 1-63 characters consisting of ASCII "
            "letters, digits, '_' or '-', and starting with a letter."
        )


def is_auto_generated_workflow_name(workflow_name: str) -> bool:
    """Return whether a name looks like ``WorkflowBuilder``'s auto-generated default.

    ``WorkflowBuilder`` names an otherwise-unnamed workflow
    ``f"WorkflowBuilder-{uuid4()}"``, which changes on every process build and is
    therefore not a stable durable identity.

    Args:
        workflow_name: The candidate name.

    Returns:
        ``True`` if the name matches the auto-generated pattern.
    """
    return bool(_AUTO_GENERATED_NAME_RE.match(workflow_name))
