// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable
#pragma warning disable IDE0005 // Extra using directive is ok.

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Agents.Workflows;
using Microsoft.Agents.Workflows.Declarative;
using Microsoft.Agents.Workflows.Declarative.Kit;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.AI.Agents;

namespace Test.Workflow;

public static class WorkflowProvider
{
    /// <summary>
    /// The root executor for a declarative workflow.
    /// </summary>
    internal sealed class MyWorkflowRootExecutor<TInput>(
        DeclarativeWorkflowOptions options,
        Func<TInput, ChatMessage>? inputTransform) :
        RootExecutor<TInput>("my_workflow_Root", options, inputTransform)
        where TInput : notnull
    {
        protected override async ValueTask ExecuteAsync(TInput message, IWorkflowContext context, CancellationToken cancellationToken)
        {
            // Set environment variables

            // Set user variables to default values
        }
    }

    internal sealed class GotoEndExecutor(FormulaSession session) : ActionExecutor(id: "goto_end", session)
    {
        protected override ValueTask ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)
        {
            // No operation
            return default;
        }
    }

    internal sealed class SendActivity1Executor(FormulaSession session) : ActionExecutor(id: "send_activity_1", session)
    {
        protected override async ValueTask ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)
        {
            string activityText =
                await context.FormatTemplateAsync(
                    """
                    NEVER 1!
                    """
                );
            AgentRunResponse response = new([new ChatMessage(ChatRole.Assistant, activityText)]);
            await context.AddEventAsync(new AgentRunResponseEvent(this.Id, response)).ConfigureAwait(false);
        }
    }

    internal sealed class SendActivity2Executor(FormulaSession session) : ActionExecutor(id: "send_activity_2", session)
    {
        protected override async ValueTask ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)
        {
            string activityText =
                await context.FormatTemplateAsync(
                    """
                    NEVER 2!
                    """
                );
            AgentRunResponse response = new([new ChatMessage(ChatRole.Assistant, activityText)]);
            await context.AddEventAsync(new AgentRunResponseEvent(this.Id, response)).ConfigureAwait(false);
        }
    }

    internal sealed class SendActivity3Executor(FormulaSession session) : ActionExecutor(id: "send_activity_3", session)
    {
        protected override async ValueTask ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)
        {
            string activityText =
                await context.FormatTemplateAsync(
                    """
                    NEVER 3!
                    """
                );
            AgentRunResponse response = new([new ChatMessage(ChatRole.Assistant, activityText)]);
            await context.AddEventAsync(new AgentRunResponseEvent(this.Id, response)).ConfigureAwait(false);
        }
    }

    internal sealed class EndAllExecutor(FormulaSession session) : ActionExecutor(id: "end_all", session)
    {
        protected override ValueTask ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)
        {
            // No operation
            return default;
        }
    }

    public static Workflow<TInput> CreateWorkflow<TInput>(
        DeclarativeWorkflowOptions options,
        Func<TInput, ChatMessage>? inputTransform = null)
        where TInput : notnull
    {
        // Create executor instances
        MyWorkflowRootExecutor<TInput> root = new(options, inputTransform);
        GotoEndExecutor gotoEnd = new(root.Session);
        SendActivity1Executor sendActivity1 = new(root.Session);
        SendActivity2Executor sendActivity2 = new(root.Session);
        SendActivity3Executor sendActivity3 = new(root.Session);
        EndAllExecutor endAll = new(root.Session);

        // Define the workflow builder
        WorkflowBuilder builder = new(root);

        // Connect executors
        builder.AddEdge(root, gotoEnd);
        builder.AddEdge(endAll, gotoEnd);
        builder.AddEdge(root, sendActivity1);
        builder.AddEdge(root, sendActivity2);
        builder.AddEdge(root, sendActivity3);
        builder.AddEdge(root, endAll);

        // Build the workflow
        return builder.Build<TInput>();
    }
}
