// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable enable
#pragma warning disable IDE0005 // Using directive is unnecessary.

using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Agents.Workflows;
using Microsoft.Agents.Workflows.Declarative;
using Microsoft.Agents.Workflows.Declarative.Extensions;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.AI.Agents;

namespace Demo.DeclarativeCode;

public static class WorkflowProvider
{
    public static Workflow<TInput> CreateWorkflow<TInput>(
        DeclarativeWorkflowOptions options,
        Func<TInput, ChatMessage>? inputTransform = null)
        where TInput : notnull
    {
        // Define the workflow builder
        DeclarativeWorkflowBuilder<TInput> builder = new("workflow", options, inputTransform); // %%% ID

        // Create executor instances
        SetvarUserInputExecutor setvarUserInput = new();
        SetvarUserNameExecutor setvarUserName = new();
        SendResultExecutor sendResult = new();

        // Connect executors
        builder.AddEdge(builder.Root, setvarUserInput);
        builder.AddEdge(setvarUserInput, setvarUserName);
        builder.AddEdge(setvarUserName, sendResult);

        // Build the workflow
        return builder.Build<TInput>();
    }
}

internal sealed class SetvarUserInputExecutor() : ActionExecutor(id: "setvar_user_input")
{
    protected override async ValueTask ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)
    {
        object? value = await context.ReadStateAsync<object>("LastMessageText", "System").ConfigureAwait(false);

        await context.QueueStateUpdateAsync("UserInput", value, "Topic").ConfigureAwait(false);
    }
}

internal sealed class SetvarUserNameExecutor() : ActionExecutor(id: "setvar_user_name")
{
    protected override async ValueTask ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)
    {
        //object? value = await context.ReadStateAsync<object>("USERNAME", "Env").ConfigureAwait(false);
        object? value = Environment.GetEnvironmentVariable("USERNAME");

        await context.QueueStateUpdateAsync("UserName", value, "Global").ConfigureAwait(false);
    }
}

internal sealed class SendResultExecutor() : ActionExecutor(id: "send_result")
{
    protected override async ValueTask ExecuteAsync(IWorkflowContext context, CancellationToken cancellationToken)
    {
        string activityText =
            await context.FormatAsync(
                """
                Hello {Global.UserName},
                You said, "{Topic.UserInput}"
                """
            );
        AgentRunResponse response = new([new ChatMessage(ChatRole.Assistant, activityText)]);
        await context.AddEventAsync(new AgentRunResponseEvent(this.Id, response)).ConfigureAwait(false);

    }
}
