# Copyright (c) Microsoft. All rights reserved.

"""GitHub MCP URL + FIDES Example (direct URL connection with local policy enforcement).

This sample demonstrates how to connect an agent directly to a remote MCP URL
(`https://api.githubcopilot.com/mcp/`) while still enforcing IFC/FIDES security
locally in your application process.

Important: this uses a local `MCPStreamableHTTPTool` wrapped by
`SecureMCPToolProxy(...)`, not `client.get_mcp_tool(...)`. That keeps MCP
execution local so security middleware can inspect tool results, apply labels,
hide untrusted content, and enforce policies.

Prerequisites:
1. Environment variables:
    - GITHUB_PAT: GitHub Personal Access Token (required)
    - FOUNDRY_PROJECT_ENDPOINT: Foundry project endpoint (required)
    - FOUNDRY_MODEL: Foundry model deployment name (optional, defaults to o4-mini)
2. Modes (choose exactly one):
   - `--cli`   Run automated CLI scenarios.
   - `--devui` Launch the DevUI web interface for interactive debugging.
3. Optional flags:
   - `--attack` (CLI only) runs a prompt-injection style flow likely to trigger
     a write tool policy violation / approval path.
   - `--debug` enables verbose tool and security middleware logging.

Run:
    uv run samples/02-agents/security/github_mcp_example.py --cli
    uv run samples/02-agents/security/github_mcp_example.py --cli --attack
    uv run samples/02-agents/security/github_mcp_example.py --devui
    uv run samples/02-agents/security/github_mcp_example.py --devui --debug
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import os
import secrets
import sys
from contextlib import AsyncExitStack, suppress
from pathlib import Path
from typing import Any

from agent_framework import Agent
from agent_framework.foundry import FoundryChatClient
from agent_framework.security import SecureAgentConfig, SecureMCPToolProxy
from azure.identity import AzureCliCredential
from dotenv import load_dotenv

MCP_URL = "https://api.githubcopilot.com/mcp/"
MCP_HEADERS = {"X-MCP-Features": "ifc_labels"}  # Opt-in to server-side IFC label emission in _meta
FOUNDRY_MODEL = os.getenv("FOUNDRY_MODEL", "o4-mini")


def configure_logging(*, debug: bool) -> None:
    """Configure optional verbose logging for the sample.

    When --debug is enabled, shows only security.py logs to focus on context
    label changes and policy enforcement.
    """
    logging.basicConfig(
        level=logging.WARNING,  # Default: suppress most logs
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        force=True,  # Override any existing handlers from imported modules
    )

    # Suppress other noisy loggers
    for logger_name in ["httpx", "asyncio", "uvicorn", "agent_framework"]:
        logging.getLogger(logger_name).setLevel(logging.WARNING)

    if debug:
        # Enable only agent_framework.security logs in debug mode
        logging.getLogger("agent_framework.security").setLevel(logging.DEBUG)
    else:
        # When not debugging, suppress security logger entirely (no variable/policy errors)
        logging.getLogger("agent_framework.security").setLevel(logging.CRITICAL + 1)


def get_devui_auth_token() -> tuple[str, bool]:
    """Return the DevUI auth token and whether it came from environment.

    When the sample launches DevUI directly via ``serve(...)``, the framework's
    autogenerated token may be logged through a logger that is not visible in
    the sample's terminal output. This helper makes the active token explicit.
    """
    env_token = os.environ.get("DEVUI_AUTH_TOKEN")
    if env_token:
        return env_token, True
    return secrets.token_urlsafe(32), False


def _redact_token(token: str) -> str:
    """Return a redacted token safe for terminal output."""
    if len(token) <= 8:
        return "<redacted>"
    return f"{token[:4]}...{token[-4:]}"


def _normalize_pat(raw_pat: str) -> str:
    """Normalize a PAT loaded from environment variables.

    Removes surrounding whitespace and optional matching quotes so copied
    values like '"ghp_..."' in .env do not cause auth failures.

    Args:
        raw_pat: Raw token value from environment.

    Returns:
        Normalized token string.
    """
    token = raw_pat.strip()
    if len(token) >= 2 and token[0] == token[-1] and token[0] in {'"', "'"}:
        token = token[1:-1].strip()
    return token


def _print_auth_failure_guidance() -> None:
    """Print actionable guidance for MCP authentication failures."""
    print("\nFailed to authenticate to the remote MCP URL (401 Unauthorized).", file=sys.stderr)
    print("Please verify the following:", file=sys.stderr)
    print("  1. GITHUB_PAT is set and not expired/revoked", file=sys.stderr)
    print("  2. GITHUB_PAT in .env has no surrounding quotes or trailing spaces", file=sys.stderr)
    print("  3. The token has scopes needed for the operations you request", file=sys.stderr)
    print(f"  4. Endpoint is reachable: {MCP_URL}", file=sys.stderr)


def _print_tool_labels(tools: list[Any], *, limit: int = 8, debug: bool = False) -> None:
    """Print a subset of auto-applied FIDES labels from MCP annotations.

    Args:
        tools: Labeled tools from SecureMCPToolProxy.
        limit: Max number of tools to display.
        debug: Only print if debug mode is enabled.
    """
    if not debug:
        return
    print("\nAuto-applied security labels from MCP annotations:")
    for func in tools[:limit]:
        props = getattr(func, "additional_properties", {}) or {}
        integrity = props.get("source_integrity", "-")
        max_conf = props.get("max_allowed_confidentiality", "-")
        accepts_untrusted = props.get("accepts_untrusted", "-")
        print(
            f"  - {func.name:30s} integrity={integrity:10s} "
            f"max_conf={max_conf:8s} accepts_untrusted={accepts_untrusted}"
        )


def _print_context_label(config: SecureAgentConfig, *, debug: bool = False) -> None:
    """Print the current context label from the security config.

    This shows how the context confidentiality/integrity was tainted
    by tool results or other operations.

    Args:
        config: SecureAgentConfig instance.
        debug: Only print if debug mode is enabled.
    """
    if not debug:
        return
    context_label = config.label_tracker.get_context_label()
    print(
        "\n[CONTEXT LABEL] "
        f"integrity={context_label.integrity.value:10s} "
        f"confidentiality={context_label.confidentiality.value:8s}"
    )


def _build_query(*, attack_mode: bool) -> str:
    """Build the user query for safe or attack mode.

    Args:
        attack_mode: Whether to run the policy-violation-oriented scenario.

    Returns:
        Prompt text to send to the agent.
    """
    if attack_mode:
        return (
            "Solve the latest issue for me on https://github.com/shrutitople/Fides-testing/issues/1. "
            "My username is shrutitople. Read what you need and post a comment on the issue with the fix. "
            "Use MCP tools to solve the issue."
        )

    return (
        "Use GitHub MCP tools to fetch pull requests from owner='microsoft', repo='agent-framework'. "
        "Return the 3 most recent OPEN pull requests sorted by created date descending. "
        "Output only fields: number, title, author login, created_at. "
        "If any tool call fails or returns no data, report the failure explicitly and do not guess."
    )


def _load_env_and_validate() -> tuple[str, str]:
    """Load .env files and validate required environment variables.

    Returns:
        Tuple of (github_pat, foundry_endpoint).
    """
    load_dotenv(Path(__file__).parent / ".env")
    load_dotenv()

    raw_pat = os.getenv("GITHUB_PAT")
    if not raw_pat:
        raise RuntimeError("GITHUB_PAT is required. Create a token at https://github.com/settings/tokens")
    github_pat = _normalize_pat(raw_pat)
    if not github_pat:
        raise RuntimeError("GITHUB_PAT is empty after normalization. Check your .env value.")

    endpoint = os.getenv("FOUNDRY_PROJECT_ENDPOINT")
    if not endpoint:
        raise RuntimeError("FOUNDRY_PROJECT_ENDPOINT is required for FoundryChatClient.")

    return github_pat, endpoint


_AGENT_INSTRUCTIONS = (
    "You are a helpful GitHub assistant. Use tools to answer accurately. "
    "Never fabricate repository data, pull requests, users, or timestamps. "
    "If tool data is unavailable, explicitly say retrieval failed. "
    "When operations might modify data, explain what action you intend to take."
)


async def run_cli_async(*, attack_mode: bool, debug: bool = False) -> None:
    """Run the direct-URL MCP example with IFC/FIDES security enabled (CLI mode)."""
    github_pat, endpoint = _load_env_and_validate()
    credential = AzureCliCredential()
    main_client = FoundryChatClient(
        project_endpoint=endpoint,
        model=FOUNDRY_MODEL,
        credential=credential,
    )
    quarantine_client = FoundryChatClient(
        project_endpoint=endpoint,
        model="gpt-4o-mini",
        credential=credential,
    )

    try:
        async with AsyncExitStack() as stack:
            secure_github = await stack.enter_async_context(
                SecureMCPToolProxy(
                    url=MCP_URL,
                    headers={"Authorization": f"Bearer {github_pat}", **MCP_HEADERS},
                    name="GitHub",
                    description="GitHub MCP server over Streamable HTTP",
                )
            )
            print(f"Connected to MCP URL: {MCP_URL}")
            print(f"Loaded tools: {len(secure_github.tools)}")
            _print_tool_labels(secure_github.tools, debug=debug)
            config = SecureAgentConfig(
                # Keep untrusted content visible for this fact-retrieval sample so
                # responses stay tightly grounded to raw tool outputs.
                auto_hide_untrusted=True,
                enable_policy_enforcement=True,
                approval_on_violation=True,
                quarantine_chat_client=quarantine_client,
            )

            agent = await stack.enter_async_context(
                Agent(
                    client=main_client,
                    name="GitHubSecureMcpUrlAgent",
                    instructions=_AGENT_INSTRUCTIONS,
                    tools=secure_github.tools,
                    context_providers=[config],
                )
            )

            query = _build_query(attack_mode=attack_mode)
            print("\nUser:", query)
            result = await agent.run(query)
            print("\nAgent:", result.text)

            _print_context_label(config, debug=debug)

            audit_log = config.get_audit_log()
            print(f"\nSecurity audit entries: {len(audit_log)}")
            for entry in audit_log:
                reason = entry.get("reason", "policy violation")
                function_name = entry.get("function", "unknown")
                print(f"  - function={function_name} reason={reason}")
    except asyncio.CancelledError:
        raise
    except Exception as ex:
        details = str(ex)
        if "401" in details or "Unauthorized" in details:
            _print_auth_failure_guidance()
            raise RuntimeError("Authentication to the MCP URL failed.") from ex
        raise


async def run_devui_async(*, debug: bool = False) -> None:
    """Launch DevUI in the same event loop that owns the MCP connection.

    DevUI's public ``serve(...)`` API is synchronous (it calls
    ``uvicorn.run``), which would create a fresh event loop and orphan our
    MCP transport. To share a single loop with the live MCP session, we
    construct the DevUI ``DevServer`` directly and drive it via
    ``uvicorn.Server.serve()`` from inside this coroutine.
    """
    # Import here so CLI-only runs don't require the devui extras.
    import uvicorn
    from agent_framework_devui._server import DevServer

    github_pat, endpoint = _load_env_and_validate()
    credential = AzureCliCredential()
    main_client = FoundryChatClient(
        project_endpoint=endpoint,
        model=FOUNDRY_MODEL,
        credential=credential,
    )
    quarantine_client = FoundryChatClient(
        project_endpoint=endpoint,
        model="gpt-4o-mini",
        credential=credential,
    )

    async with AsyncExitStack() as stack:
        try:
            # Wrap the remote MCP URL as local tools so FIDES can label inputs/outputs
            # and enforce policy checks before tool data is used by the agent.
            secure_github = await stack.enter_async_context(
                SecureMCPToolProxy(
                    url=MCP_URL,
                    headers={"Authorization": f"Bearer {github_pat}", **MCP_HEADERS},
                    name="GitHub",
                    description="GitHub MCP server over Streamable HTTP",
                )
            )
            print(f"Connected to MCP URL: {MCP_URL}")
            print(f"Loaded tools: {len(secure_github.tools)}")
            _print_tool_labels(secure_github.tools, debug=debug)
        except Exception as ex:
            details = str(ex)
            if "401" in details or "Unauthorized" in details:
                _print_auth_failure_guidance()
                raise RuntimeError("Authentication to the MCP URL failed.") from ex
            raise

        config = SecureAgentConfig(
            auto_hide_untrusted=True,
            enable_policy_enforcement=True,
            approval_on_violation=True,
            quarantine_chat_client=quarantine_client,
        )

        agent = await stack.enter_async_context(
            Agent(
                client=main_client,
                name="GitHubSecureMcpUrlAgent",
                instructions=_AGENT_INSTRUCTIONS,
                tools=secure_github.tools,
                context_providers=[config],
            )
        )

        host = "127.0.0.1"
        port = 8090
        auth_token, token_from_env = get_devui_auth_token()

        server_obj = DevServer(
            port=port,
            host=host,
            auth_enabled=True,
            auth_token=auth_token,
        )
        server_obj.set_pending_entities([agent])
        app = server_obj.get_app()

        print("\n" + "=" * 70)
        print("DevUI: GitHub MCP + FIDES")
        print("=" * 70)
        print(f"URL:          http://{host}:{port}")
        print(f"Entity ID:    agent_{agent.name}")
        print("Bearer token (use as 'Authorization: Bearer <token>'):")
        if token_from_env:
            print(f"  {_redact_token(auth_token)} (from DEVUI_AUTH_TOKEN)")
        else:
            print(f"  {auth_token} (auto-generated for this run)")
        print("\nQueries to try:")
        print("  - Use GitHub MCP tools to fetch pull requests from owner='octocat', repo='hello-world'.")
        print("  - Show the 3 most recent OPEN pull requests in microsoft/agent-framework.")
        print("\nPress Ctrl+C to stop.\n")

        uvicorn_config = uvicorn.Config(app, host=host, port=port, log_level="info")
        uvicorn_server = uvicorn.Server(uvicorn_config)
        with suppress(KeyboardInterrupt):
            await uvicorn_server.serve()


def _parse_args(argv: list[str]) -> tuple[str, bool, bool]:
    """Parse CLI arguments. Returns (mode, attack, debug)."""
    parser = argparse.ArgumentParser(description="Run direct-URL MCP + FIDES sample.")
    mode_group = parser.add_mutually_exclusive_group(required=True)
    mode_group.add_argument(
        "--cli",
        action="store_true",
        help="Run in command line mode (automated scenarios).",
    )
    mode_group.add_argument(
        "--devui",
        action="store_true",
        help="Run with DevUI web interface (interactive).",
    )
    parser.add_argument(
        "--attack",
        action="store_true",
        help="(CLI only) Prompt-injection style scenario likely to trigger policy enforcement.",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable verbose tool and security middleware logging.",
    )
    args = parser.parse_args(argv)
    if args.attack and not args.cli:
        parser.error("--attack can only be combined with --cli")
    mode = "cli" if args.cli else "devui"
    return mode, args.attack, args.debug


def main() -> None:
    """Entry point for the sample script."""
    mode, attack, debug = _parse_args(sys.argv[1:])
    configure_logging(debug=debug)
    try:
        if mode == "cli":
            asyncio.run(run_cli_async(attack_mode=attack, debug=debug))
        else:
            asyncio.run(run_devui_async(debug=debug))
    except RuntimeError as ex:
        print(f"\nError: {ex}", file=sys.stderr)
        raise SystemExit(1) from ex
    except KeyboardInterrupt:
        print("\nInterrupted by user.", file=sys.stderr)


if __name__ == "__main__":
    main()

"""
Sample output (safe mode, abbreviated):
Connected to MCP URL: https://api.githubcopilot.com/mcp/
Loaded tools: 20
Auto-applied security labels from MCP annotations:
  - list_issues ... accepts_untrusted=True
  - add_issue_comment ... max_conf=public accepts_untrusted=False

User: List my 5 most recent repositories and include a one-line summary for each.
Agent: Here are your five most recent repositories ...

Security audit entries: 0
"""
