from __future__ import annotations

import argparse
import asyncio
import logging
import os
import secrets
import sys
from contextlib import AsyncExitStack, suppress
from pathlib import Path
from typing import Any

from agent_framework import Agent, MCPStreamableHTTPTool
from agent_framework.foundry import FoundryChatClient
from agent_framework.security import SecureAgentConfig, SecureMCPToolProxy
from azure.identity import AzureCliCredential
from dotenv import load_dotenv

FOUNDRY_MODEL = os.getenv("FOUNDRY_MODEL", "gpt-5")

def configure_logging(*, debug: bool) -> None:
    """Configure optional verbose logging for the sample.

    When --debug is enabled, shows only security.py logs to focus on context
    label changes and policy enforcement.
    """
    logging.basicConfig(
        level=logging.WARNING,  # Default: suppress most logs
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        force=True,  # Override any existing handlers from imported modules
    )

    # Suppress other noisy loggers
    for logger_name in ["httpx", "asyncio", "uvicorn", "agent_framework"]:
        logging.getLogger(logger_name).setLevel(logging.WARNING)

    if debug:
        # Enable only agent_framework.security logs in debug mode
        logging.getLogger("agent_framework.security").setLevel(logging.DEBUG)
    else:
        # When not debugging, suppress security logger entirely (no variable/policy errors)
        logging.getLogger("agent_framework.security").setLevel(logging.CRITICAL + 1)


def get_devui_auth_token() -> tuple[str, bool]:
    """Return the DevUI auth token and whether it came from environment.

    When the sample launches DevUI directly via ``serve(...)``, the framework's
    autogenerated token may be logged through a logger that is not visible in
    the sample's terminal output. This helper makes the active token explicit.
    """
    env_token = os.environ.get("DEVUI_AUTH_TOKEN")
    if env_token:
        return env_token, True
    return secrets.token_urlsafe(32), False


def _redact_token(token: str) -> str:
    """Return a redacted token safe for terminal output."""
    if len(token) <= 8:
        return "<redacted>"
    return f"{token[:4]}...{token[-4:]}"


def _print_tool_labels(tools: list[Any], *, limit: int = 8, debug: bool = False) -> None:
    """Print a subset of auto-applied FIDES labels from MCP annotations.

    Args:
        tools: Labeled tools from SecureMCPToolProxy.
        limit: Max number of tools to display.
        debug: Only print if debug mode is enabled.
    """
    if not debug:
        return
    print("\nAuto-applied security labels from MCP annotations:")
    for func in tools[:limit]:
        props = getattr(func, "additional_properties", {}) or {}
        integrity = props.get("source_integrity", "-")
        max_conf = props.get("max_allowed_confidentiality", "-")
        accepts_untrusted = props.get("accepts_untrusted", "-")
        print(
            f"  - {func.name:30s} integrity={integrity:10s} "
            f"max_conf={max_conf:8s} accepts_untrusted={accepts_untrusted}"
        )


def _print_context_label(config: SecureAgentConfig, *, debug: bool = False) -> None:
    """Print the current context label from the security config.

    This shows how the context confidentiality/integrity was tainted
    by tool results or other operations.

    Args:
        config: SecureAgentConfig instance.
        debug: Only print if debug mode is enabled.
    """
    if not debug:
        return
    context_label = config.label_tracker.get_context_label()
    print(
        "\n[CONTEXT LABEL] "
        f"integrity={context_label.integrity} "
        f"confidentiality={context_label.confidentiality}"
    )

def _load_env_and_validate() -> tuple[str, str]:
    """Load .env files and validate required environment variables.

    Returns:
        Tuple of (github_pat, foundry_endpoint).
    """
    load_dotenv(Path(__file__).parent / ".env")
    load_dotenv()

    endpoint = os.getenv("FOUNDRY_PROJECT_ENDPOINT")
    if not endpoint:
        raise RuntimeError("FOUNDRY_PROJECT_ENDPOINT is required for FoundryChatClient.")

    return endpoint


_AGENT_INSTRUCTIONS = (
    "Act as my high-autonomy productivity agent: read amd respond to my emails/teams messages, infer intent, "
    "and complete tasks using available workiq mcp server tools without asking unnecessary questions. Reply if you have to, do not ask me for confirmation."
)


async def run_cli_async(*, debug: bool = False, gateway_port: int = 9090) -> None:
    """Run the sample in CLI mode with two MCP proxies (WorkIQ email + teams)."""
    endpoint = _load_env_and_validate()
    credential = AzureCliCredential()
    main_client = FoundryChatClient(
        project_endpoint=endpoint,
        model=FOUNDRY_MODEL,
        credential=credential,
    )

    teams_url = f"http://localhost:{gateway_port}/mcp/WorkIQ-TeamsServer"
    mail_url = f"http://localhost:{gateway_port}/mcp/WorkIQ-MailTools"

    async with AsyncExitStack() as stack:
        secure_mcp_1 = await stack.enter_async_context(
            SecureMCPToolProxy(
                mcp_tool=MCPStreamableHTTPTool(
                    name="WorkIQ-TeamsServer",
                    url=teams_url,
                    description="WorkIQ Teams MCP server via local proxy",
                    tool_name_prefix="teams",
                ),
                gateway_policy=True,
            )
        )
        print(f"Connected to MCP proxy: {teams_url}")
        print(f"Loaded tools (Teams): {len(secure_mcp_1.tools)}")
        _print_tool_labels(secure_mcp_1.tools, debug=debug)

        secure_mcp_2 = await stack.enter_async_context(
            SecureMCPToolProxy(
                mcp_tool=MCPStreamableHTTPTool(
                    name="WorkIQ-MailServer",
                    url=mail_url,
                    description="WorkIQ Email MCP server via local proxy",
                    tool_name_prefix="mail",
                ),
                gateway_policy=True,
            )
        )
        print(f"Connected to MCP proxy: {mail_url}")
        print(f"Loaded tools (Email): {len(secure_mcp_2.tools)}")
        _print_tool_labels(secure_mcp_2.tools, debug=debug)

        all_tools = secure_mcp_1.tools + secure_mcp_2.tools

        config = SecureAgentConfig(
            auto_hide_untrusted=False,
            enable_policy_enforcement=True,
            approval_on_violation=True,
            quarantine_chat_client=None,
        )

        agent = await stack.enter_async_context(
            Agent(
                client=main_client,
                name="WorkIQSecureAgent",
                instructions=_AGENT_INSTRUCTIONS,
                tools=all_tools,
                context_providers=[config],
            )
        )

        # query = "Read my latest emails and summarize them."
        query = "Handle my recent unread emails."
        print("\nUser:", query)
        result = await agent.run(query)
        print("\nAgent:", result.text)

        _print_context_label(config, debug=debug)

        audit_log = config.get_audit_log()
        print(f"\nSecurity audit entries: {len(audit_log)}")
        for entry in audit_log:
            reason = entry.get("reason", "policy violation")
            function_name = entry.get("function", "unknown")
            print(f"  - function={function_name} reason={reason}")


async def run_devui_async(*, debug: bool = False, gateway_port: int = 9090) -> None:
    """Launch DevUI with both MCP proxies."""
    import uvicorn
    from agent_framework_devui._server import DevServer

    endpoint = _load_env_and_validate()
    credential = AzureCliCredential()
    main_client = FoundryChatClient(
        project_endpoint=endpoint,
        model=FOUNDRY_MODEL,
        credential=credential,
    )
    quarantine_client = FoundryChatClient(
        project_endpoint=endpoint,
        model="gpt-4o-mini",
        credential=credential,
    )

    mail_url = f"http://localhost:{gateway_port}/mcp/WorkIQ-MailTools"

    async with AsyncExitStack() as stack:
        secure_mcp = await stack.enter_async_context(
            SecureMCPToolProxy(
                mcp_tool=MCPStreamableHTTPTool(
                    name="WorkIQ-MailServer",
                    url=mail_url,
                    description="WorkIQ Email MCP server via local proxy",
                    tool_name_prefix="mail",
                    terminate_on_close=False,
                    load_prompts=False,
                ),
                gateway_policy=True,
            )
        )
        print(f"Connected to MCP proxy: {mail_url}")
        print(f"Loaded tools (Email): {len(secure_mcp.tools)}")
        _print_tool_labels(secure_mcp.tools, debug=debug)

        config = SecureAgentConfig(
            auto_hide_untrusted=False,
            enable_policy_enforcement=True,
            approval_on_violation=True,
            quarantine_chat_client=None,
        )

        agent = await stack.enter_async_context(
            Agent(
                client=main_client,
                name="WorkIQSecureAgent",
                instructions=_AGENT_INSTRUCTIONS,
                tools=secure_mcp.tools,
                context_providers=[config],
            )
        )

        host = "127.0.0.1"
        port = 8090
        auth_token, token_from_env = get_devui_auth_token()

        server_obj = DevServer(
            port=port,
            host=host,
            auth_enabled=True,
            auth_token=auth_token,
        )
        server_obj.set_pending_entities([agent])
        app = server_obj.get_app()

        print("\n" + "=" * 70)
        print("DevUI: WorkIQ Email MCP + FIDES")
        print("=" * 70)
        print(f"URL:          http://{host}:{port}")
        print(f"Entity ID:    agent_{agent.name}")
        print("Bearer token (use as 'Authorization: Bearer <token>'):")
        if token_from_env:
            print(f"  {_redact_token(auth_token)} (from DEVUI_AUTH_TOKEN)")
        else:
            print(f"  {auth_token} (auto-generated for this run)")
        print("\nPress Ctrl+C to stop.\n")

        uvicorn_config = uvicorn.Config(app, host=host, port=port, log_level="info")
        uvicorn_server = uvicorn.Server(uvicorn_config)
        with suppress(KeyboardInterrupt):
            await uvicorn_server.serve()


def _parse_args(argv: list[str]) -> tuple[str, bool]:
    """Parse CLI arguments. Returns (mode, debug)."""
    parser = argparse.ArgumentParser(description="Run WorkIQ Email/Teams MCP + FIDES sample.")
    mode_group = parser.add_mutually_exclusive_group(required=True)
    mode_group.add_argument("--cli", action="store_true", help="Run in command line mode.")
    mode_group.add_argument("--devui", action="store_true", help="Run with DevUI web interface.")
    parser.add_argument("--debug", action="store_true", help="Enable verbose security logging.")
    parser.add_argument(
        "--gateway-port",
        type=int,
        default=9090,
        help="Port of the local Fides gateway (default: 9090).",
    )
    args = parser.parse_args(argv)
    mode = "cli" if args.cli else "devui"
    return mode, args.debug, args.gateway_port


def main() -> None:
    """Entry point for the sample script."""
    mode, debug, gateway_port = _parse_args(sys.argv[1:])
    configure_logging(debug=debug)
    try:
        if mode == "cli":
            asyncio.run(run_cli_async(debug=debug, gateway_port=gateway_port))
        else:
            asyncio.run(run_devui_async(debug=debug, gateway_port=gateway_port))
    except RuntimeError as ex:
        print(f"\nError: {ex}", file=sys.stderr)
        raise SystemExit(1) from ex
    except KeyboardInterrupt:
        print("\nInterrupted by user.", file=sys.stderr)


if __name__ == "__main__":
    main()
