#
# This workflow demonstrates an agent that requires tool approval
# in a loop responding to user input.
#
# Example input: 
# What is the soup of the day?
#
kind: Workflow
trigger:

  kind: OnConversationStart
  id: workflow_demo
  actions:

    - kind: SetVariable
      id: set_location
      variable: Local.UserLocation
      value: =System.LastMessage.Text

    - kind: InvokeAzureAgent
      id: invoke_search
      conversationId: =System.ConversationId
      agent:
        name: LocationAgent
      input:
        arguments:
          location: =Local.UserLocation
        externalLoop:
          when: =Upper(System.LastMessage.Text) <> "EXIT"
