// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Agents.AI.Workflows;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Moq;

namespace Microsoft.Agents.AI.Foundry.Hosting.UnitTests;

public class ResilientWorkflowExecutorIdHealthCheckTests
{
    [Fact]
    public async Task CheckHealthAsync_NotResilient_ReturnsHealthyEvenWithAutoIdsAsync()
    {
        // Arrange: a workflow with auto-generated executor ids, but the host is not resilient.
        var host = BuildWorkflowAgent(stableIds: false);
        var check = new ResilientWorkflowExecutorIdHealthCheck(isResilient: () => false, agents: () => [host]);

        // Act
        var result = await check.CheckHealthAsync(NewContext());

        // Assert: unstable ids are harmless without recovery, so the check is a no-op.
        Assert.Equal(HealthStatus.Healthy, result.Status);
    }

    [Fact]
    public async Task CheckHealthAsync_Resilient_StableIds_ReturnsHealthyAsync()
    {
        // Arrange: resilient host, workflow whose agents have explicit stable ids.
        var host = BuildWorkflowAgent(stableIds: true);
        var check = new ResilientWorkflowExecutorIdHealthCheck(isResilient: () => true, agents: () => [host]);

        // Act
        var result = await check.CheckHealthAsync(NewContext());

        // Assert
        Assert.Equal(HealthStatus.Healthy, result.Status);
    }

    [Fact]
    public async Task CheckHealthAsync_Resilient_AutoGeneratedIds_ReturnsUnhealthyAsync()
    {
        // Arrange: resilient host, workflow whose agents rely on the default random id.
        var host = BuildWorkflowAgent(stableIds: false);
        var check = new ResilientWorkflowExecutorIdHealthCheck(isResilient: () => true, agents: () => [host]);

        // Act
        var result = await check.CheckHealthAsync(NewContext());

        // Assert: the auto-generated ids break resume, so readiness fails with an actionable message.
        Assert.Equal(HealthStatus.Unhealthy, result.Status);
        Assert.Contains("stable Id", result.Description, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task CheckHealthAsync_Resilient_ExplicitGuidId_ReturnsHealthyAsync()
    {
        // Arrange: resilient host whose agents were given explicit ids that happen to be GUIDs.
        // This is the case the previous string heuristic got wrong: a caller-supplied GUID is a
        // stable id, so it must be treated as healthy. HasAutoGeneratedId is false here.
        var a = new IdAgent(Guid.NewGuid().ToString("N"), name: "french");
        var b = new IdAgent(Guid.NewGuid().ToString("N"), name: "spanish");
        var host = new WorkflowBuilder(a).AddEdge(a, b).Build().AsAIAgent(name: "host");
        var check = new ResilientWorkflowExecutorIdHealthCheck(isResilient: () => true, agents: () => [host]);

        // Act
        var result = await check.CheckHealthAsync(NewContext());

        // Assert
        Assert.Equal(HealthStatus.Healthy, result.Status);
    }

    [Fact]
    public async Task CheckHealthAsync_Resilient_SingleAgentWithoutWorkflow_ReturnsHealthyAsync()
    {
        // Arrange: a plain (non-workflow) agent exposes no internal executor ids to match.
        var single = new IdAgent(id: null, name: "single");
        var check = new ResilientWorkflowExecutorIdHealthCheck(isResilient: () => true, agents: () => [single]);

        // Act
        var result = await check.CheckHealthAsync(NewContext());

        // Assert
        Assert.Equal(HealthStatus.Healthy, result.Status);
    }

    private static AIAgent BuildWorkflowAgent(bool stableIds)
    {
        var a = stableIds ? new IdAgent("french", "french") : new IdAgent(id: null, name: null);
        var b = stableIds ? new IdAgent("spanish", "spanish") : new IdAgent(id: null, name: null);
        return new WorkflowBuilder(a).AddEdge(a, b).Build().AsAIAgent(name: "host");
    }

    private static HealthCheckContext NewContext() =>
        new()
        {
            Registration = new HealthCheckRegistration(
                name: "foundry-resilient-workflow-ids",
                instance: Mock.Of<IHealthCheck>(),
                failureStatus: HealthStatus.Unhealthy,
                tags: null),
        };

    /// <summary>
    /// Minimal agent whose id is stable when an explicit id is supplied, and defaults to the
    /// framework's random per-process id when it is not. Used to build workflows with either stable
    /// or auto-generated executor ids.
    /// </summary>
    private sealed class IdAgent : AIAgent
    {
        private readonly string? _id;

        public IdAgent(string? id, string? name)
        {
            this._id = id;
            this.Name = name;
        }

        protected override string? IdCore => this._id;
        public override string? Name { get; }

        protected override Task<AgentResponse> RunCoreAsync(
            IEnumerable<Microsoft.Extensions.AI.ChatMessage> messages,
            AgentSession? session,
            AgentRunOptions? options,
            CancellationToken cancellationToken = default) =>
            throw new NotImplementedException();

        protected override IAsyncEnumerable<AgentResponseUpdate> RunCoreStreamingAsync(
            IEnumerable<Microsoft.Extensions.AI.ChatMessage> messages,
            AgentSession? session,
            AgentRunOptions? options,
            CancellationToken cancellationToken = default) =>
            throw new NotImplementedException();

        protected override ValueTask<AgentSession> CreateSessionCoreAsync(
            CancellationToken cancellationToken = default) =>
            throw new NotImplementedException();

        protected override ValueTask<System.Text.Json.JsonElement> SerializeSessionCoreAsync(
            AgentSession session,
            System.Text.Json.JsonSerializerOptions? jsonSerializerOptions,
            CancellationToken cancellationToken = default) =>
            throw new NotImplementedException();

        protected override ValueTask<AgentSession> DeserializeSessionCoreAsync(
            System.Text.Json.JsonElement serializedState,
            System.Text.Json.JsonSerializerOptions? jsonSerializerOptions,
            CancellationToken cancellationToken = default) =>
            throw new NotImplementedException();
    }
}
