kind: workflow
trigger:
  kind: OnConversationStart
  id: my_workflow
  actions:
    - kind: SetVariable
      id: set_variable_input_task
      variable: Local.LatestMessage
      value: =UserMessage(System.LastMessageText)
    - kind: CreateConversation
      id: create_student_conversation
      conversationId: Local.StudentConversationId
    - kind: CreateConversation
      id: create_teacher_conversation
      conversationId: Local.TeacherConversationId
    - kind: InvokeAzureAgent
      id: student_agent
      description: The student node
      conversationId: =Local.StudentConversationId
      agent:
        name: asst_GhxNLZ2xLNzUb5HDsPpC4BHx
      input:
        messages: =Local.LatestMessage
      output:
        messages: Local.LatestMessage
    - kind: SendActivity
      id: send_activity_student
      activity: {Last(Local.LatestMessage).Text}
    - kind: InvokeAzureAgent
      id: teacher_agent
      description: The teacher node
      conversationId: =Local.TeacherConversationId
      agent:
        name: asst_wkRCEW27TWPHUyU3rlXclRPD
      input:
        messages: =Local.LatestMessage
      output:
        messages: Local.LatestMessage
    - kind: SendActivity
      id: send_activity_teacher
      activity: {Last(Local.LatestMessage).Text}
    - kind: SetVariable
      id: set_variable_turncount
      variable: Local.TurnCount
      value: =Local.TurnCount + 1
    - kind: ConditionGroup
      id: completion_check
      conditions:
        - condition: =!IsBlank(Find("CONGRATULATIONS", Upper(Last(Local.LatestMessage).Text)))
          id: check_done
          actions:
            - kind: EndConversation
              id: end_workflow
        - condition: =Local.TurnCount >= 4
          id: check_turn_count_exceeded
          actions:
            - kind: SendActivity
              id: send_activity_tired
              activity: Let's try again later...I am tired.
      elseActions:
        - kind: GotoAction
          id: goto_student_agent
          actionId: student_agent
 