#
# This workflow demonstrates sequential agent interaction to develop product marketing copy.
#
# Example input: 
# An eco-friendly stainless steel water bottle that keeps drinks cold for 24 hours.
#
# Any Foundry Agent may be used to provide the response.
# See: ./setup/QuestionAgent.yaml
#
kind: Workflow
trigger:

  kind: OnConversationStart
  id: workflow_demo
  actions:

    - kind: InvokeAzureAgent
      id: invoke_agent
      conversationId: =System.ConversationId
      agent:
        name: JsonSchemaAgent
      output:
        messages: Local.AgentResponseItems
        responseObject: Local.AgentResponseObject

    - kind: SendActivity
      id: show_message
      activity: {First(Local.AgentResponseItems).Text}

    - kind: SendActivity
      id: show_object
      activity: {Local.AgentResponseObject}



