#
# This workflow demonstrates an agent interacting with user input.
#
kind: Workflow
trigger:

  kind: OnConversationStart
  id: workflow_demo
  actions:
    
    - kind: SendActivity
      id: activity_start
      activity: BEGIN
  
    - kind: RequestExternalInput
      id: request_requirements
      variable: Local.UserInput

    - kind: SendActivity
      id: activity_agent
      activity: CONTINUE ({Local.UserInput.Text})

    - kind: InvokeAzureAgent
      id: gather_requirements
      conversationId: =System.ConversationId
      agent:
        name: ServiceAgent
      externalLoop:
        when: =true

    - kind: SendActivity
      id: activity_done
      activity: DONE


